Repository planme-app/front, pull requests merged in 2023-06, with the labels that each got.

#47 [Feat] #46 add routine post api
  src/backend/models/Routine.ts
  src/backend/repositories/PrismaRoutineInstanceRepository.ts
  src/backend/repositories/PrismaRoutineRepository.ts
  src/backend/repositories/RoutineInstanceRepository.ts
  src/backend/repositories/RoutineRepository.ts
  src/backend/services/RoutineService.ts
  src/pages/api/user/[userId]/routines.ts
Labels: bug, enhancement

#50 [Feat] #49 add routine edit api
  src/backend/repositories/PrismaRoutineInstanceRepository.ts
  src/backend/repositories/RoutineInstanceRepository.ts
  src/backend/services/RoutineService.ts
  src/pages/api/user/[userId]/routine-instance/[routineInstanceId].ts
Labels: enhancement

#51 Feat/#41/add routine, routine/detail, mypage function
  package-lock.json
  package.json
  public/fail.png
  public/success.png
  src/components/atoms/CustomButton.tsx
  src/components/atoms/Days.tsx
  src/components/atoms/DetailTitle.tsx
  src/components/atoms/ModalAtom.tsx
  src/components/atoms/RoutineDate.tsx
  src/components/atoms/RoutinePercent.tsx
  src/components/atoms/UseTimer.tsx
  src/components/organisms/BottomBar.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/MypageSlide.tsx
  src/components/organisms/RoutineCard.tsx
  src/components/organisms/RoutineDetailBoolButton.tsx
  src/components/organisms/RoutineDetailCountButton.tsx
  src/components/organisms/RoutineDetailTimeButton.tsx
  src/controllers/services/api.ts
  src/pages/loading/index.tsx
  src/pages/login/index.tsx
  src/pages/routine/detail.tsx
  src/pages/routine/detail/[routinedetail].tsx
  src/pages/routine/index.tsx
  src/stores/routineStore.ts
  tsconfig.json
Labels: enhancement

#52 [Feat] #48 add routine page
  src/components/atoms/MypageLayout.tsx
  src/components/atoms/RoutineTemplate.tsx
  src/components/organisms/BottomBar.tsx
  src/components/organisms/RoutineTemplateAddText.tsx
  src/components/organisms/RoutineTemplateAddType.tsx
  src/components/organisms/RoutineTemplateAddWeek.tsx
  src/components/organisms/RoutineTemplateCard.tsx
  src/controllers/services/api.ts
  src/pages/profile/index.tsx
  src/pages/routine/index.tsx
  src/pages/routine/template/add.tsx
  src/pages/routine/template/index.tsx
  src/stores/routineStore.ts
Labels: enhancement

#56 [Fix] #55 change get routines API
  src/backend/services/RoutineService.ts
  src/pages/api/user/[userId]/routines.ts
Labels: bug

#57 [Feat] #54 edit routine api,tomorrow routine,all detail
  src/components/atoms/CustomButton.tsx
  src/components/atoms/MyInfo.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/RoutineCard.tsx
  src/controllers/application/PutRoutine.ts
  src/controllers/services/api.ts
  src/pages/routine/detail/[routinedetail].tsx
  src/pages/routine/index.tsx
  src/stores/routineStore.ts
Labels: enhancement

#58 [Feat] #53 add calendar to routine page
  package-lock.json
  package.json
  src/components/atoms/AlertMessage.tsx
  src/components/atoms/Days.tsx
  src/components/atoms/ModalAtom.tsx
  src/components/organisms/Header.tsx
  src/pages/login/index.tsx
  src/pages/routine/template/add.tsx
  src/pages/signup/index.tsx
  src/stores/routineStore.ts
Labels: enhancement

#62 [fix] #61 typeError, delete unused file
  src/components/atoms/UseTimer.tsx
  src/components/organisms/MypageSlide.tsx
Labels: bug

#64 [Refactor] #63 refactor version 0.1.0
  src/components/atoms/AlertMessage.tsx
  src/components/atoms/CustomButton.tsx
  src/components/atoms/Days.tsx
  src/components/atoms/DetailTitle.tsx
  src/components/atoms/DialogAtom.tsx
  src/components/atoms/LoginBody.tsx
  src/components/atoms/MainBody.tsx
  src/components/atoms/ModalAtom.tsx
  src/components/atoms/MyInfo.tsx
  src/components/atoms/RoutineDate.tsx
  src/components/atoms/RoutinePercent.tsx
  src/components/atoms/RoutineTemplate.tsx
  src/components/atoms/UseTimer.tsx
  src/components/organisms/BottomBar.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/RoutineCard.tsx
  src/components/organisms/RoutineDetailBoolButton.tsx
  src/components/organisms/RoutineDetailCountButton.tsx
  src/components/organisms/RoutineTemplateAddText.tsx
  src/components/organisms/RoutineTemplateAddType.tsx
  src/components/organisms/RoutineTemplateAddWeek.tsx
  src/components/organisms/RoutineTemplateCard.tsx
  src/components/organisms/SignupCard.tsx
  src/controllers/services/api.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/pages/profile/index.tsx
  src/pages/routine/detail/[routinedetail].tsx
  src/pages/routine/index.tsx
  src/pages/routine/template/add.tsx
  src/pages/routine/template/index.tsx
  src/pages/signup/index.tsx
  src/stores/routineStore.ts
Labels: Refactor

#72 [Design] #65 login,loading page,logo change
  public/Logo(titleO).png
  public/Logo(titleX).png
  public/SubTitle.png
  public/Title.png
  public/font/Title_Light.otf
  public/font/Title_Medium.otf
  public/font/style.css
  public/gogleIcon.png
  public/kakaoIcon.png
  src/components/atoms/LoginBody.tsx
  src/components/organisms/Header.tsx
  src/pages/_app.tsx
  src/pages/loading/index.tsx
  src/pages/login/index.tsx
  src/pages/routine/detail/[routinedetail].tsx
  src/pages/routine/index.tsx
  src/styles/theme.ts
Labels: enhancement

#67 [Feat] #66 cypress init setting
  .eslintrc.json
  .gitignore
  cypress.config.ts
  cypress/e2e/signup.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.d.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/components/atoms/TextField.tsx
  src/components/organisms/SignupCard.tsx
  src/pages/signup/index.tsx
Labels: enhancement
